spring:
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/zufang_0422?useUnicode=true&characterEncoding=utf-8
    driverClassName: net.sf.log4jdbc.DriverSpy
    username: root
    password: root
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  jpa:
    database: MySQL
    show-sql: false
    properties.hibernate.format_sql: true
    properties.hibernate.show_sql: false
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
