spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zufang_0422?characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
jpa:
  database: MySQL
  show-sql: true
  hibernate:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
